Update codebase
PlaceholderAPI/WorldGuard-Expansion pull request #19
Opened 2021-04-20 08:50 UTC by BeakerThe1st

Just a simple update to the codebase 👍 

This PR also moves from the wrapper being used to the native WorldGuard API. Not sure if there's a reason that the wrapper is being used, but this seems much better :)

2021-04-20 11:47 UTC, Andre601 commented
The WG Wrapper guarantees support for pre-7 versions.
If the API does have a version independant API now should this be okay

2021-04-20 12:13 UTC, BeakerThe1st commented
> The WG Wrapper guarantees support for pre-7 versions.
> If the API does have a version independant API now should this be okay

Ah, I thought it had something to do with backwards compatibility. However, WorldGuard's documentation mentions "without breaking a significant amount of backwards compatibility" so while I haven't tested it yet, fingers crossed that it is version independent 🤞

2021-10-04 15:30 UTC, iGabyTM requested changes

2021-10-04 15:30 UTC, iGabyTM commented on src/main/java/com/extendedclip/papi/expansion/worldguard/WorldGuardExpansion.java
>      }
- Could use a [`StringJoiner`](https://docs.oracle.com/javase/8/docs/api/java/util/StringJoiner.html)
- Chain the `append()` calls

2021-10-04 15:36 UTC, iGabyTM requested changes

2021-10-04 15:36 UTC, iGabyTM commented on src/main/java/com/extendedclip/papi/expansion/worldguard/WorldGuardExpansion.java
> +            Random rand = new Random();
Keep an instance at the top of the class instead of creating a new one every time this method is used.

2022-10-01 21:15 UTC, iGabyTM commented
Hey @BeakerThe1st are you going to finish this? 😃

2024-05-13 14:36 UTC, closed without merging